### ISSUE TITLE
Remove ITogglableMod

### ISSUE THREAD

**Issue by flibber-hk** [fifty-six/HollowKnight.QoL#48]
Disabling QoL through the toggleable mod system doesn't properly disable QoL; certain modules are unable to be disabled because of how they function. I believe the expected behaviour should be that mods which don't appear on the mod list don't affect the game, so this would be unexpected. (The expected way to disable QoL would be to either disable all toggleable modules and leave the mod installed, or simply disable QoL through Scarab/etc.)

**Comment by fifty-six** [comment]
Which modules? As far as I can recall I've added a disable to all of them? The only real thing off the top of my head is unmodifying Playmaker FSMs that are static after a save load – but I think that's fine anyways. With it disabled, it also doesn't enable any of the modules on startup, which I think matches the expected behavior as well.

**Comment by flibber-hk** [comment]
Hmm - honestly I don't have anything more concrete than 

> when "QoL On|Off" is set to Off, the mod is still functioning

(I haven't attempted to verify this assertion). 

I think based on the lack of strong evidence I'll close this issue, but I'll reopen if I get concrete evidence that it's broken.
